[package]
name = "vulkan-object"
version = "0.1.0+1.4.341"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"

[build-dependencies]
schemars = "0.8"
serde_json = "1"
typify = "0.5"
